services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi:application
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:17.0
    env_file:
      - db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: