services:
  web:
    env_file:
      - .env.prod
    environment:
      - DJANGO_ENV=production
      - DJANGO_SETTINGS_MODULE=app.settings.prod
    command: gunicorn --workers 3 --timeout 120 --bind 0.0.0.0:8000 app.wsgi:application
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.25
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - static_volume:/code/app/staticfiles
      - media_volume:/code/app/media
    depends_on:
      - web