# Generated by Django 5.1.4 on 2024-12-30 20:20

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.CustomUser.path_to_avatar, verbose_name='avatar'),
        ),
    ]
