# Generated by Django 5.1.4 on 2025-01-30 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_accountsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsettings',
            options={'verbose_name_plural': 'Account Settings'},
        ),
    ]
