# Generated by Django 5.1.4 on 2024-12-30 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_category_product_catergory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catergory',
            new_name='category',
        ),
    ]
