# Generated by Django 5.1.4 on 2024-12-30 20:20

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=orders.models.Product.path_to_product, verbose_name='preview'),
        ),
    ]
