# Generated by Django 5.1.4 on 2025-01-15 20:30

from django.db import migrations


def set_default_customer_name(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(customer_name__isnull=True).update(
        customer_name='Jane Doe')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_customer_name'),
    ]

    operations = [
        migrations.RunPython(set_default_customer_name),
    ]
