# Generated by Django 5.1.4 on 2025-01-15 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_productcategory_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.store'),
            preserve_default=False,
        ),
    ]
