# Generated by Django 5.1.4 on 2025-01-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_store_alter_product_store_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Store',
            new_name='store',
        ),
    ]
