# Generated by Django 5.1.4 on 2025-01-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_rename_store_order_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='today_sales',
        ),
        migrations.RemoveField(
            model_name='store',
            name='total_customers',
        ),
        migrations.RemoveField(
            model_name='store',
            name='total_orders',
        ),
        migrations.RemoveField(
            model_name='store',
            name='total_sales',
        ),
    ]
