# Generated by Django 5.1.4 on 2025-01-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_store_today_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
