# Generated by Django 5.1.4 on 2025-01-23 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_store_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='revenue',
        ),
    ]
