# Generated by Django 5.1.4 on 2025-07-21 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer', models.CharField(blank=True, max_length=255, null=True)),
                ('printer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.store')),
            ],
        ),
    ]
