# Generated by Django 5.1.4 on 2025-07-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_storeconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconfig',
            name='printer_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
