# Generated by Django 5.1.4 on 2025-07-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_storeconfig_printer_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='printer_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='printer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='StoreConfig',
        ),
    ]
